name: sign2speech
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - numpy<2.0.0
  - pydantic>=2.0.0
  - fastapi>=0.100.0
  - uvicorn>=0.20.0
  - pytorch
  - pip:
      - mediapipe==0.10.5
      - pose-format>=0.3.2
      - uvicorn[standard]>=0.20.0
      - sign-language-segmentation @ git+https://github.com/sign-language-processing/segmentation
